// export const DEVICE_URL = "http://192.168.1.41"; // this will be the IP of Device on which DB is Hosted.
export const DEVICE_URL = "http://192.168.1.37"; // this will be the IP of Device on which DB is Hosted.
export const DB_PORT = "3030";

export const EMPLOYEE_TOKEN = "EMPLOYEE_TOKEN";
export const EMPLOYEE_ID = "EMPLOYEE_ID";``
export const EMPLOYEE_FULLNAME = "EMPLOYEE_FULLNAME";
export const EMPLOYEE_PLANTS = "EMPLOYEE_PLANTS";
export const EMPLOYEE_STORAGELOCATION = "EMPLOYEE_STORAGELOCATION";
export const EMPLOYEE_DESIGNATION = "EMPLOYEE_DESIGNATION";
export const EMPLOYEE_CARDNUMBER = "EMPLOYEE_CARDNUMBER";
export const EMPLOYEE_USERNAME = "EMPLOYEE_USERNAME";
export const EMPLOYEE_ISSANCTIONAUTHORITY = "EMPLOYEE_ISSANCTIONAUTHORITY";
export const EMPLOYEE_MODULEACCESS = "EMPLOYEE_MODULEACCESS";
export const EMPLOYEE_REPORTMODULES = "EMPLOYEE_REPORTMODULES";
export const EMPLOYEE_ALLMODULES = "EMPLOYEE_ALLMODULES";
export const EMPLOYEE_SELECTEDWEBPORTAL = "EMPLOYEE_SELECTEDWEBPORTAL";
export const EMPLOYEE_PLANT = "EMPLOYEE_PLANT";
export const EMPLOYEE_DEFAULTPLANT = "EMPLOYEE_DEFAULTPLANT";
export const EMPLOYEE_DEPT = "EMPLOYEE_DEPT";
export const EMPLOYEE_CELL = "EMPLOYEE_CELL";
export const EMPLOYEE_ISADMIN = "EMPLOYEE_ISADMIN";
export const EMPLOYEE_TYPE = "EMPLOYEE_TYPE";
export const ECPTKEY = "F54651SDDVHJDS";
export const DESKTOPESSENTIALS = "desktopessentials";
export const DB_URL = DEVICE_URL + ":" + DB_PORT;
export const DB_APIURL = DB_URL + "/api/v1/";

export const ALL_STORAGELOCATIONS = "ALL_STORAGELOCATIONS";
export const FG_MATERIALS = "FG_MATERIALS";
export const SFG_MATERIALS = "SFG_MATERIALS";

export const COMPANYNAME = 'ZF Steering Gear (India) Limited';
export const WEBAPPTITLE = 'WAREHOUSE AUTOMATION';
export const WEBAPPSUBTITLE = 'WAREHOUSE AUTOMATION PLATFORM';